spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mariadb-0.mariadb.base.svc.cluster.local:3306/my_wiki
    username: root
    password: "123456"

project:
  root-directory: 'C:\Users\wujj\Desktop\MyWiki\MyWiki'
  table-prefix: 't_'

templates:
  service:
    module: ''

tables:
  - logic-name: t_trend_model_platform

packages:
  service: junjie.fun.mywiki.service
  service-impl: junjie.fun.mywiki.service.impl
  mapper: junjie.fun.mywiki.mapper
  entity: junjie.fun.mywiki.entity
  request: junjie.fun.mywiki.request
  response: junjie.fun.mywiki.response
  response-data: junjie.fun.mywiki.response.data
  enums: junjie.fun.mywiki.enums
  controller: junjie.fun.mywiki.controller